name: 'ois_analytics'
version: '1.0.0'
config-version: 2

profile: 'ois'

model-paths: ["dbt/models"]
analysis-paths: ["dbt/analysis"]
test-paths: ["dbt/tests"]
data-paths: ["dbt/data"]
macro-paths: ["dbt/macros"]
snapshot-paths: ["dbt/snapshots"]

target-path: "dbt/target"
clean-targets:
  - "dbt/target"
  - "dbt/dbt_packages"

models:
  ois_analytics:
    materialized: view
